
app1:
  aks_resource_group: 'AksResourceGroup'
  aks_cluster_name: 'AksClusterName'
  login_server: 'LoginServer'
  auto_merge:
    des: true
    pre: true
    pro: false
  services:
    - app-server
    - app-client
    - app-api

app2:
  aks_resource_group: 'AksResourceGroup'
  aks_cluster_name: 'AksClusterName'
  login_server: 'LoginServer'
  auto_merge:
    dev: true
    pre: true
    pro: false
  services:
    - proxy
    - dns

