name: Test release

on:
  release:
    types: [released]

env:
  stage: 'STAGE_ENVAR'
  service_name: 'SERVICE_NAME_ENVAR'
  state_repo: 'test-state'
  
jobs:
  show-actor:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Print Github actor
        run: |
          echo $GITHUB_ACTOR
          echo ${{ github.actor }}
          
      - name: Dispatch release to state repo
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/prefapp/${{ env.state_repo }}/dispatches \
            -d '{"event_type":"test-dispatch-event"
                 "client_payload": {
                   "environment": "${{ env.stage }}",
                   "service": "${{ env.service_name }}",
                   "actor": "${{ github.actor }}",
                   "image": "nombre_imagen" }}'
