name: Failure
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Try to fail
        run: exit 1
        
      - name: Try to fail
        if: ${{ always() }}
        run: echo "Always always runs hahaha"
