name: Workflow PR Closed
on:
  pull_request:
    branches: [main]
    paths:
      - 'app1/**'
      - 'app2/**'
    state: [closed]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Check for code folder changes in PR branch
        id: code-changes
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          PR_FILES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X GET -G $URL | jq -r '.[] | .filename')
          echo $PR_FILES
          for path in $PR_FILES; do
            if [[ $path = app1/* || $path = app2/* ]]; then
              APP=$( echo $path | cut -d '/' -f 1 )
              ENV=$( echo $path | cut -d '/' -f 2 )
              echo "Changes in code folders detected: '$path'"
              echo "application/chart detected: '$APP'"
              echo "environment detected: '$ENV'"
              echo ::set-output name=detected::true
              break
            fi
          done
