name: Workflow PR Closed
on:
  pull_request:
    branches: [main]
    state: [closed]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Check for code folder changes in PR branch
        id: code-changes
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          PR_FILES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X GET -G $URL | jq -r '.[] | .filename')
          echi $PR_FILES
          for path in $PR_FILES; do
            if [[ $path = code/* || $path = .github/workflows/code* ]]; then
              echo "Changes in code folders detected: '$path'"
              echo ::set-output name=detected::true
              break
            fi
          done
