name: Tag with semver
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
      
      - name: Get poetry version
        id: poetry_ver
        run: |
                VERSION=$( poetry version | cut -d ' ' -f 2 )
                echo "::set-output name=VERSION::$VERSION"
                echo $VERSION
                
      - name: Tag snapshot
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.poetry_ver.outputs.VERSION }}

      
