name: Test
on:
  workflow_dispatch:
    inputs:
      tenant:
        description: 'Tenant'
        required: true
        default: ''
      application:
        description: 'Application'     
        required: true
        default: ''
      environment:
        description: 'Environment'     
        required: true
        default: ''
      services:
        description: 'Services'     
        required: true
        default: ''
      image:
        description: 'New image'     
        required: true
        default: ''
      reviewers:
        description: 'PR Reviewers'     
        required: false
        default: ''

env:
  repo_git_user: 'github-actions'
  repo_git_mail: 'github-actions@github.com'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Update image
        id: gh
        uses: prefapp/action-state-repo-update-image@feature/v3
        with:
          tenant: ${{ github.event.inputs.tenant }}
          application: ${{ github.event.inputs.application }}
          environment: ${{ github.event.inputs.environment }}
          services: ${{ github.event.inputs.services }}
          image: ${{ github.event.inputs.image }}
          reviewers: ${{ github.event.inputs.reviewers }}

      # Use the output from the `hello` step
      #- name: Get the output time
      #  run: echo "The time was ${{ steps.hello.outputs.time }}"
