name: test action-flavour-images-matrix-generator

on:
  workflow_dispatch:

  release:
    types: [prereleased, released]

  push:
    branches:
      - main

  pull_request:   
    types: [labeled, synchronize]

jobs:
  calculate-matrix:
    env:
      repository: prefappacr.azurecr.io/apps/backend/hellok8s
    runs-on: ubuntu-latest
    outputs: 
      matrix: ${{ steps.calculate-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        
      - name: calculate-matrix-v1
        id: calculate-matrix-v1
        uses: prefapp/action-flavour-images-matrix-generator@v1
        with:
          matrix_output: matrix
          repository: ${{ env.repository }}
          
      - run: echo ${{ steps.calculate-matrix-v1.outputs.matrix }}
      
      - name: calculate-matrix-test
        id: calculate-matrix-test
        uses: prefapp/action-flavour-images-matrix-generator@feature/build-images-json-schema
        with:
          matrix_output: matrix
          repository: ${{ env.repository }}
          
      - run: echo ${{ steps.calculate-matrix-test.outputs.matrix }}
