name: test_v4_action_state_repo_update_image
on:
  workflow_dispatch:

env:
  repo_git_user: "github-actions"
  repo_git_mail: "github-actions@github.com"
  input_json: |
    {
      "inputs": [
        {
          "tenant": "tenant1",
          "app": "release1",
          "env": "dev",
          "service_names": ["proxy"],
          "image": "image_proxy:tag",
          "reviewers": ["AlbertFemenias"]
        },
        {
          "tenant": "tenant1",
          "app": "release1",
          "env": "pre",
          "service_names": ["dns"],
          "image": "image_dns:tag",
          "reviewers": ["AlbertFemenias"]
        }
      ]
    }
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Update image
        id: gh
        uses: prefapp/action-state-repo-update-image@v4
        with:
          input_matrix: ${{ env.input_json }}
