name: Test
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Source branch'     
        required: true
        default: ''

env:
  repo_git_user: 'github-actions'
  repo_git_mail: 'github-actions@github.com'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo context
        id: gh
        uses: prefapp/action-state-repo-generate-pr@feature/v1
        with:
          target_branch: ${{ github.event.inputs.branch }}
          secret_token: ${{ secrets.GITHUB_TOKEN }}

      # Use the output from the `hello` step
      #- name: Get the output time
      #  run: echo "The time was ${{ steps.hello.outputs.time }}"
